import './globals.css'
import type { Metadata } from 'next'
import Link from 'next/link'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {

  return (
    <html lang="en">
      <body className={inter.className}>
        <nav>
          <ul style={{padding: '1rem', listStyle: 'none', display: 'flex', justifyContent: 'end'}}>
            <li style={{paddingRight: '1rem'}}><Link href={'/'}>Home</Link></li>
            <li><Link href={'/about'}>About</Link></li>
          </ul>
        </nav>
        {children}
      </body>
    </html>
  )
}
