import './globals.css'
import type { Metadata } from 'next'
import Link from 'next/link'
import Script from 'next/script'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {

  return (
    <html lang="en">
      <body className={inter.className}>
        <nav>
          <ul style={{padding: '1rem', listStyle: 'none', display: 'flex', justifyContent: 'end'}}>
            <li style={{paddingRight: '1rem'}}><Link href={'/'}>Home</Link></li>
            <li><Link href={'/about'}>About</Link></li>
          </ul>
        </nav>
        {children}
        {/* <!-- Google tag (gtag.js) --> */}
        <Script strategy="afterInteractive" src="https://www.googletagmanager.com/gtag/js?id=G-67QLSPYMZY"/>
        <Script
          id='google-analytics'
          strategy="afterInteractive"
          dangerouslySetInnerHTML={{
            __html: `
            window.dataLayer = window.dataLayer || [];
            function gtag(){dataLayer.push(arguments);}
            gtag('js', new Date());

            gtag('config', 'G-67QLSPYMZY');
            `,
            }}
        />
      </body>
    </html>
  )
}
