import './globals.css'
import type { Metadata } from 'next'
import Link from 'next/link'
import Script from 'next/script'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {

  return (
    <html lang="en">
      <head>
        <Script
            id='google-tag-manager'
            strategy="afterInteractive"
            dangerouslySetInnerHTML={{
              __html: `
              <!-- Google Tag Manager -->
(function(w,d,s,l,i){w[l]=w[l]||[];w[l].push({'gtm.start':
new Date().getTime(),event:'gtm.js'});var f=d.getElementsByTagName(s)[0],
j=d.createElement(s),dl=l!='dataLayer'?'&l='+l:'';j.async=true;j.src=
'https://www.googletagmanager.com/gtm.js?id='+i+dl;f.parentNode.insertBefore(j,f);
})(window,document,'script','dataLayer','GTM-NX82GHPD');
<!-- End Google Tag Manager -->
              `,
              }}
          />
      </head>
      <body className={inter.className}>
      {/* <!-- Google Tag Manager (noscript) --> */}
        <noscript><iframe src="https://www.googletagmanager.com/ns.html?id=GTM-NX82GHPD"
        height="0" width="0" style={{display:'none', visibility: 'hidden'}}></iframe></noscript>
        {/* <!-- End Google Tag Manager (noscript) --> */}
        <nav>
          <ul style={{padding: '1rem', listStyle: 'none', display: 'flex', justifyContent: 'end'}}>
            <li style={{paddingRight: '1rem'}}><Link href={'/'}>Home</Link></li>
            <li><Link href={'/about'}>About</Link></li>
          </ul>
        </nav>
        {children}
        {/* <!-- Google tag (gtag.js) --> */}
        <Script strategy="afterInteractive" src="https://www.googletagmanager.com/gtag/js?id=G-67QLSPYMZY"/>
        <Script
          id='google-analytics'
          strategy="afterInteractive"
          dangerouslySetInnerHTML={{
            __html: `
            window.dataLayer = window.dataLayer || [];
            function gtag(){dataLayer.push(arguments);}
            gtag('js', new Date());

            gtag('config', 'G-67QLSPYMZY');
            `,
            }}
        />
      </body>
    </html>
  )
}
